algoritmo "areaRetangulo"
// Função :
// Autor :
// Data : 20/02/2019
// Seção de Declarações 
var
   ladoMaior: real
   ladoMenor: real

   
inicio

// Seção de Comandos 
   escreva("Digite o lado maior do retangulo: ")
   leia(ladoMaior)
   escreva("Digite o lado menor do retangulo: ")
   leia(ladoMenor)

   escreva("A area do retangulo é: ", ladoMaior * ladoMenor)
fimalgoritmo
